apiVersion: v1
kind: ConfigMap
metadata:
  name: fab-db-config
  namespace: hydrofab
data:
  DB_HOST: "fab-postgres"
  DB_PORT: "5432"
  DB_NAME: "hydrofab"
  DB_USER: "fab"
---
apiVersion: v1
kind: Secret
metadata:
  name: fab-db-secret
  namespace: hydrofab
type: Opaque
stringData:
  DB_PASSWORD: "fab_secret"
  POSTGRES_PASSWORD: "fab_secret"
  CONNECTION_STRING: "Host=fab-postgres;Port=5432;Database=hydrofab;Username=fab;Password=fab_secret"
